FROM rocm/pytorch:rocm7.1.1_ubuntu24.04_py3.12_pytorch_release_2.9.1

# Install uv
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        curl \
        libvulkan-dev \
        glslc \
        make

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

COPY . /app
WORKDIR /app

ENV UV_SYSTEM_PYTHON=1
ENV UV_BREAK_SYSTEM_PACKAGES=1

RUN CMAKE_ARGS="-DGGML_VULKAN=ON -DGGML_RPC=ON" pip install -e ".[rocm]"
ENTRYPOINT ["python3", "-m", "llama_supercharged"]
