FROM rocm/pytorch:rocm7.1.1_ubuntu24.04_py3.12_pytorch_release_2.9.1

# Install uv
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        curl \
        libvulkan-dev \
        glslc
RUN pip install uv

# Install the package
COPY . /app
WORKDIR /app

# Run the development server
ENTRYPOINT ["bash", "entrypoint.sh"]
